Repository prgrms-be-devcourse/NBE1_2_Team02, pull requests merged in 2024-11, with the labels that each got.

#93 [FEAT] 럭키 드로우 구현
  src/main/java/com/example/book_your_seat/luckydraw/domain/LuckyDrawHistory.java
  src/main/java/com/example/book_your_seat/luckydraw/repository/LuckyDrawHistoryRepository.java
  src/main/java/com/example/book_your_seat/luckydraw/service/LuckyDrawScheduler.java
  src/main/java/com/example/book_your_seat/reservation/domain/Reservation.java
  src/main/java/com/example/book_your_seat/reservation/repository/ReservationRepository.java
  src/main/java/com/example/book_your_seat/user/UserConst.java
  src/main/java/com/example/book_your_seat/user/mail/MailConst.java
  src/main/java/com/example/book_your_seat/user/mail/util/MailUtil.java
  src/main/resources/templates/luckyDrawTemplate.html
Labels: 🔥 매운맛, 🌟 Feature

#97 [FEAT] 이미지 저장 로직 구현
  build.gradle
  src/main/java/com/example/book_your_seat/config/S3Config.java
  src/main/java/com/example/book_your_seat/image/domain/Image.java
  src/main/java/com/example/book_your_seat/image/repository/ImageRepository.java
  src/main/java/com/example/book_your_seat/s3/FileExtension.java
  src/main/java/com/example/book_your_seat/s3/S3ImageController.java
  src/main/java/com/example/book_your_seat/s3/S3ImageService.java
  src/main/java/com/example/book_your_seat/s3/dto/UploadRequest.java
  src/main/java/com/example/book_your_seat/s3/dto/UploadResponse.java
Labels: 🔥 매운맛, 🌟 Feature

#98 [REFACTOR] 대기열 리팩토링
  src/main/java/com/example/book_your_seat/payment/service/facade/PaymentFacade.java
  src/main/java/com/example/book_your_seat/queue/controller/QueueController.java
  src/main/java/com/example/book_your_seat/queue/repository/QueueRedisRepository.java
  src/main/java/com/example/book_your_seat/queue/scheduler/QueueScheduler.java
  src/main/java/com/example/book_your_seat/queue/service/command/QueueCommandService.java
  src/main/java/com/example/book_your_seat/queue/service/facade/QueueFacade.java
  src/main/java/com/example/book_your_seat/queue/service/query/QueueQueryService.java
  src/main/java/com/example/book_your_seat/seat/SeatConst.java
  src/main/java/com/example/book_your_seat/seat/controller/dto/SelectSeatRequest.java
  src/main/java/com/example/book_your_seat/seat/service/facade/SeatFacade.java
  src/test/java/com/example/book_your_seat/service/queue/QueueServiceTest.java
  src/test/java/com/example/book_your_seat/service/seat/SeatCommandServiceImplTest.java
Labels: ⚒️ Refactoring, 💡 Enhancement

#99 Feat 콘서트 리뷰 기능
  src/main/java/com/example/book_your_seat/concert/ConcertConst.java
  src/main/java/com/example/book_your_seat/concert/service/query/ConcertQueryService.java
  src/main/java/com/example/book_your_seat/review/ReviewConst.java
  src/main/java/com/example/book_your_seat/review/controller/ReviewController.java
  src/main/java/com/example/book_your_seat/review/controller/dto/ReviewCreateRequest.java
  src/main/java/com/example/book_your_seat/review/controller/dto/ReviewListResponse.java
  src/main/java/com/example/book_your_seat/review/controller/dto/ReviewResponse.java
  src/main/java/com/example/book_your_seat/review/controller/dto/ReviewUpdateDTO.java
  src/main/java/com/example/book_your_seat/review/domain/Review.java
  src/main/java/com/example/book_your_seat/review/repository/ReviewRepository.java
  src/main/java/com/example/book_your_seat/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/example/book_your_seat/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/example/book_your_seat/review/service/command/ReviewCommandService.java
  src/main/java/com/example/book_your_seat/review/service/facade/ReviewFacade.java
  src/main/java/com/example/book_your_seat/review/service/query/ReviewQueryService.java
  src/main/java/com/example/book_your_seat/user/repository/UserRepository.java
  src/main/resources/script.js
  src/test/java/com/example/book_your_seat/service/review/ReviewServiceTest.java
Labels: 🌟 Feature
