Repository prgrms-be-devcourse/NBE1_2_Team02, pull requests merged in 2024-10, with the labels that each got.

#32 [FEAT] 대기열 구현
  build.gradle
  src/main/java/com/example/book_your_seat/BookYourSeatApplication.java
  src/main/java/com/example/book_your_seat/common/util/JwtConst.java
  src/main/java/com/example/book_your_seat/common/util/JwtUtil.java
  src/main/java/com/example/book_your_seat/config/RedisConfig.java
  src/main/java/com/example/book_your_seat/coupon/facade/CouponCommandFacade.java
  src/main/java/com/example/book_your_seat/queue/QueueConst.java
  src/main/java/com/example/book_your_seat/queue/controller/QueueController.java
  src/main/java/com/example/book_your_seat/queue/controller/dto/QueueResponse.java
  src/main/java/com/example/book_your_seat/queue/controller/dto/TokenResponse.java
  src/main/java/com/example/book_your_seat/queue/repository/QueueRedisRepository.java
  src/main/java/com/example/book_your_seat/queue/scheduler/QueueScheduler.java
  src/main/java/com/example/book_your_seat/queue/service/QueueCommandService.java
  src/main/java/com/example/book_your_seat/queue/service/QueueCommandServiceImpl.java
  src/main/java/com/example/book_your_seat/queue/service/QueueQueryService.java
  src/main/java/com/example/book_your_seat/queue/service/QueueQueryServiceImpl.java
  src/main/java/com/example/book_your_seat/queue/service/facade/QueueService.java
  src/main/java/com/example/book_your_seat/queue/service/facade/QueueServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/example/book_your_seat/IntegralTestSupport.java
  src/test/java/com/example/book_your_seat/concurrent/PessimisticTest.java
  src/test/java/com/example/book_your_seat/service/concert/ConcertServiceTest.java
  src/test/java/com/example/book_your_seat/service/concert/ConcertTest.java
  src/test/java/com/example/book_your_seat/service/coupon/CouponServiceTest.java
  src/test/java/com/example/book_your_seat/service/queue/QueueServiceTest.java
  src/test/resources/application.yml
Labels: 🔥 매운맛, 🌟 Featrue

#52 [FIX] merge conflict 해결
  src/test/java/com/example/book_your_seat/service/coupon/UserCommandServiceImplTest.java
  src/test/java/com/example/book_your_seat/service/user/UserCommandServiceImplTest.java
Labels: 🔥 Hotfix

#58 48 feat slack 알림 기능
  build.gradle
  src/main/java/com/example/book_your_seat/common/constants/Constants.java
  src/main/java/com/example/book_your_seat/common/controller/TestErrorAPI.java
  src/main/java/com/example/book_your_seat/common/entity/color/Color.java
  src/main/java/com/example/book_your_seat/common/exhandler/ExControllerAdvice.java
  src/main/java/com/example/book_your_seat/common/service/SlackFacade.java
  src/main/java/com/example/book_your_seat/common/service/SlackService.java
  src/main/java/com/example/book_your_seat/common/service/SlackServiceImpl.java
  src/main/java/com/example/book_your_seat/concert/ConcertConst.java
  src/main/java/com/example/book_your_seat/payment/PaymentConst.java
  src/main/java/com/example/book_your_seat/payment/controller/PaymentController.java
  src/main/java/com/example/book_your_seat/payment/controller/dto/response/ConfirmResponse.java
  src/main/java/com/example/book_your_seat/reservation/ReservationConst.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🌟 Featrue

#59 [Feature] 구역별 가격 추가
  src/main/java/com/example/book_your_seat/payment/service/facade/PaymentFacadeImpl.java
  src/main/java/com/example/book_your_seat/seat/SeatConst.java
  src/main/java/com/example/book_your_seat/seat/domain/Seat.java
  src/main/java/com/example/book_your_seat/seat/domain/Zone.java
  src/main/java/com/example/book_your_seat/seat/service/facade/SeatFacade.java
  src/main/java/com/example/book_your_seat/seat/service/facade/SeatFacadeImpl.java
  src/main/java/com/example/book_your_seat/seat/service/query/SeatQueryService.java
  src/main/java/com/example/book_your_seat/seat/service/query/SeatQueryServiceImpl.java
  src/test/java/com/example/book_your_seat/service/payment/PaymentServiceTest.java
  src/test/java/com/example/book_your_seat/service/seat/SeatCommandServiceImplTest.java
  src/test/java/com/example/book_your_seat/service/seat/SeatQueryServiceTest.java
Labels: 🌟 Featrue

#60 [FEAT] 회원가입 시 Mail 인증 받기
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/com/example/book_your_seat/BookYourSeatApplication.java
  src/main/java/com/example/book_your_seat/common/util/JwtUtil.java
  src/main/java/com/example/book_your_seat/concert/ConcertConst.java
  src/main/java/com/example/book_your_seat/concert/domain/Concert.java
  src/main/java/com/example/book_your_seat/config/security/SecurityConfig.java
  src/main/java/com/example/book_your_seat/config/security/jwt/SecurityJwtUtil.java
  src/main/java/com/example/book_your_seat/payment/PaymentConst.java
  src/main/java/com/example/book_your_seat/payment/service/facade/PaymentFacadeImpl.java
  src/main/java/com/example/book_your_seat/queue/repository/QueueRedisRepository.java
  src/main/java/com/example/book_your_seat/queue/util/QueueJwtUtil.java
  src/main/java/com/example/book_your_seat/reservation/ReservationConst.java
  src/main/java/com/example/book_your_seat/seat/SeatConst.java
  src/main/java/com/example/book_your_seat/seat/controller/SeatController.java
  src/main/java/com/example/book_your_seat/seat/service/facade/SeatFacade.java
  src/main/java/com/example/book_your_seat/seat/service/query/SeatQueryServiceImpl.java
  src/main/java/com/example/book_your_seat/user/UserConst.java
  src/main/java/com/example/book_your_seat/user/controller/UserController.java
  src/main/java/com/example/book_your_seat/user/mail/MailConst.java
  src/main/java/com/example/book_your_seat/user/mail/repository/MailRedisRepository.java
  src/main/java/com/example/book_your_seat/user/mail/repository/util/MailUtil.java
  src/main/java/com/example/book_your_seat/user/mail/service/MailService.java
  src/main/java/com/example/book_your_seat/user/mail/service/MailServiceImpl.java
  src/main/java/com/example/book_your_seat/user/service/command/UserCommandServiceImpl.java
  src/main/java/com/example/book_your_seat/user/service/facade/UserFacade.java
  src/main/java/com/example/book_your_seat/user/service/facade/UserFacadeImpl.java
  src/main/java/com/example/book_your_seat/user/service/query/UserQueryService.java
  src/main/java/com/example/book_your_seat/user/service/query/UserQueryServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/emailTemplate.html
  src/test/java/com/example/book_your_seat/service/payment/PaymentServiceTest.java
  src/test/java/com/example/book_your_seat/service/queue/QueueServiceTest.java
  src/test/java/com/example/book_your_seat/service/seat/SeatQueryServiceTest.java
  src/test/java/com/example/book_your_seat/service/user/UserCommandServiceImplTest.java
  src/test/resources/application.yml
Labels: 🌟 Featrue

#64 [FIX] Swagger 설정 수정
  src/main/java/com/example/book_your_seat/concert/controller/AdminConcertController.java
  src/main/java/com/example/book_your_seat/concert/controller/ConcertController.java
  src/main/java/com/example/book_your_seat/config/SwaggerConfig.java
  src/main/java/com/example/book_your_seat/coupon/controller/CouponController.java
  src/main/java/com/example/book_your_seat/coupon/controller/UserCouponController.java
  src/main/java/com/example/book_your_seat/coupon/facade/CouponQueryFacade.java
  src/main/java/com/example/book_your_seat/coupon/facade/CouponQueryService.java
  src/main/java/com/example/book_your_seat/queue/controller/QueueController.java
  src/main/java/com/example/book_your_seat/seat/controller/SeatController.java
  src/test/java/com/example/book_your_seat/service/coupon/CouponServiceTest.java
  src/test/java/com/example/book_your_seat/service/coupon/UserCouponServiceImplTest.java
Labels: 💧 순한맛

#66 [FEAT] 테스트, 시연용 관리자 Role 획득 API 추가
  src/main/java/com/example/book_your_seat/concert/controller/AdminConcertController.java
  src/main/java/com/example/book_your_seat/concert/controller/ConcertController.java
  src/main/java/com/example/book_your_seat/concert/service/ConcertQueryServiceImpl.java
  src/main/java/com/example/book_your_seat/config/SwaggerConfig.java
  src/main/java/com/example/book_your_seat/user/controller/UserController.java
  src/main/java/com/example/book_your_seat/user/domain/User.java
  src/main/java/com/example/book_your_seat/user/service/command/UserCommandService.java
  src/main/java/com/example/book_your_seat/user/service/command/UserCommandServiceImpl.java
  src/main/java/com/example/book_your_seat/user/service/facade/UserFacade.java
  src/main/java/com/example/book_your_seat/user/service/facade/UserFacadeImpl.java
Labels: 🌟 Featrue

#73 [REFACTOR] User 도메인 패키지 구조 리팩토링
  src/main/java/com/example/book_your_seat/user/mail/service/MailService.java
  src/main/java/com/example/book_your_seat/user/mail/service/MailServiceImpl.java
  src/main/java/com/example/book_your_seat/user/mail/util/MailUtil.java
  src/main/java/com/example/book_your_seat/user/service/command/AddressCommandService.java
  src/main/java/com/example/book_your_seat/user/service/command/AddressCommandServiceImpl.java
  src/main/java/com/example/book_your_seat/user/service/command/UserCommandService.java
  src/main/java/com/example/book_your_seat/user/service/command/UserCommandServiceImpl.java
  src/main/java/com/example/book_your_seat/user/service/facade/UserFacade.java
  src/main/java/com/example/book_your_seat/user/service/facade/UserFacadeImpl.java
  src/main/java/com/example/book_your_seat/user/service/query/AddressQueryService.java
  src/main/java/com/example/book_your_seat/user/service/query/AddressQueryServiceImpl.java
  src/main/java/com/example/book_your_seat/user/service/query/UserQueryService.java
  src/main/java/com/example/book_your_seat/user/service/query/UserQueryServiceImpl.java
  src/test/java/com/example/book_your_seat/service/user/UserCommandServiceTest.java
Labels: 💧 순한맛
